create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text unique,
  country text,
  organization text,
  pin_hash text,
  password_hash text,
  password_salt text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.application_settings (
  id bigint generated by default as identity primary key,
  applications_open boolean not null default false,
  closed_message text not null default 'Applications are currently closed.',
  updated_at timestamptz not null default now()
);

insert into public.application_settings (applications_open, closed_message)
select false, 'Applications are currently closed.'
where not exists (select 1 from public.application_settings);
