-- KOICA YLP in-app application submissions.
-- Run once in Supabase SQL Editor.

create table if not exists public.application_submissions (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  track text not null check (track in ('public', 'private')),
  full_name text not null,
  email text not null,
  phone text not null,
  country text not null,
  organization text not null,
  file_path text not null,
  file_name text not null,
  file_mime text not null,
  file_size bigint not null default 0,
  status text not null default 'submitted' check (status in ('submitted','reviewing','accepted','rejected')),
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists application_submissions_submitted_at_idx
  on public.application_submissions (submitted_at desc);
create index if not exists application_submissions_track_idx
  on public.application_submissions (track);
create index if not exists application_submissions_email_idx
  on public.application_submissions (lower(email));

alter table public.application_submissions enable row level security;

insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'application-submissions',
  'application-submissions',
  false,
  10485760,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/octet-stream'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
