import fs from "node:fs";
import path from "node:path";
import { Router } from "express";
import { auth } from "../middleware/auth.js";
import { resourceDir, presentationDir, backendDir } from "../config/env.js";
import { getContent, getModule, getResource } from "../repositories/contentRepository.js";
import { getUserProgress, saveUserProgress } from "../repositories/progressRepository.js";
import { calculateProgress, compileCalendar } from "../services/lmsService.js";
const router=Router();
function resolveFile(filePath,runtimeDir,legacyDir){if(!filePath)return null;const candidates=path.isAbsolute(filePath)?[path.resolve(filePath)]:[path.resolve(path.dirname(runtimeDir),"..",filePath),path.resolve(backendDir,filePath)];const roots=[runtimeDir,legacyDir].map((r)=>path.resolve(r)+path.sep);return candidates.find((c)=>roots.some((r)=>c.startsWith(r))&&fs.existsSync(c))||null;}
router.get("/content",auth,(req,res)=>{const content=getContent();res.json({content});});
router.get("/dashboard",auth,(req,res)=>{const content=getContent();const modules=(content.modules||[]).filter((m)=>!m.track||m.track===req.user.track),progress=getUserProgress(req.user.id);res.json({user:{id:req.user.id,name:req.user.name,country:req.user.country,track:req.user.track,cohort:req.user.cohort,role:req.user.role||"participant"},announcements:content.announcements||[],progress:calculateProgress(modules,progress),modules:modules.map((m)=>({...m,...calculateProgress([m],progress)}))});});
router.get("/calendar",auth,(req,res)=>res.json({days:compileCalendar(getContent().modules||[],req.user.track)}));
router.get("/modules/:id",auth,(req,res)=>{const m=getModule(req.params.id);if(!m)return res.status(404).json({error:"Module not found."});if(m.track&&m.track!==req.user.track)return res.status(403).json({error:"That module belongs to the other track."});const progress=getUserProgress(req.user.id);res.json({module:{...m,lessons:(m.lessons||[]).map((l)=>({...l,done:Boolean(progress.lessons?.[`${m.id}:${l.id}`])}))}});});
router.post("/progress",auth,(req,res)=>{const {moduleId,lessonId,done}=req.body||{};const m=getModule(String(moduleId||"")),l=m?.lessons?.find((x)=>x.id===String(lessonId||""));if(!m||!l||(m.track&&m.track!==req.user.track))return res.status(404).json({error:"Module or lesson not found."});if(typeof done!=="boolean")return res.status(400).json({error:"done must be a boolean."});const p=getUserProgress(req.user.id);p.lessons=p.lessons||{};const key=`${moduleId}:${lessonId}`;if(done)p.lessons[key]=new Date().toISOString();else delete p.lessons[key];saveUserProgress(req.user.id,p);res.json({ok:true,done:Boolean(done)});});
router.get("/resources",auth,(req,res)=>res.json({resources:(getContent().resources||[]).filter((r)=>!r.track||r.track===req.user.track)}));
router.get("/resources/:id/download",auth,(req,res)=>{const r=getResource(req.params.id);if(!r)return res.status(404).json({error:"Resource not found."});if(r.track&&r.track!==req.user.track)return res.status(403).json({error:"That resource belongs to the other track."});const full=resolveFile(r.filePath,resourceDir,path.join(backendDir,"uploads","resources"));if(!full)return res.status(404).json({error:"The resource file is missing."});res.download(full,r.originalFileName||path.basename(full));});
router.get("/modules/:id/presentations/:presentationId/download",auth,(req,res)=>{const m=getModule(req.params.id);if(!m)return res.status(404).json({error:"Module not found."});if(m.track&&m.track!==req.user.track)return res.status(403).json({error:"That module belongs to the other track."});const p=(m.presentations||[]).find((x)=>x.id===req.params.presentationId);if(!p?.filePath)return res.status(404).json({error:"Presentation not found."});const full=resolveFile(p.filePath,presentationDir,path.join(backendDir,"uploads","module-presentations"));if(!full)return res.status(404).json({error:"The presentation file is missing."});res.download(full,p.originalFileName||path.basename(full));});
export default router;
